spring.application.name=payment-service
eureka.client.service-url.defaultZone=http://service-discovery:8080/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# URL base for ticket service (use service name on Docker network)
ticket.service.url=http://ticket-service:8080
