# Variáveis
@auth = http://localhost:8081
@gateway = http://localhost:8082
@events = http://localhost:8083
@history = http://localhost:8084
@payment = http://localhost:8085
@ticket = http://localhost:8086
@discovery = http://localhost:8080

### Auth - Criar usuário
# @name createUser
POST {{auth}}/users
Content-Type: application/json

{
  "name": "João",
  "email": "joao1@example.com",
  "password": "minhasenha123"
}

### Definir userId para uso nas próximas requisições
@userId = {{createUser.response.body.id}}

### Auth - Login com senha (retorna accessToken)
# @name login
POST {{auth}}/auth/login/password
Content-Type: application/json

{
  "email": "joao1@example.com",
  "password": "minhasenha123"
}

### Definir accessToken para uso nas próximas requisições
@accessToken = {{login.response.body.token}}

### Ticket Service - Criar reserva
# @name createReservation
POST {{ticket}}/api/reservations?userId=5614c11e-6c12-4280-8e1e-92ce8c9df331&eventId=11111111-1111-1111-1111-111111111111&ttlSeconds=600
Content-Type: application/json
Authorization: Bearer {{accessToken}}

[
  "A1",
  "A2"
]

### Definir reservationId para uso nas próximas requisições
@reservationId = {{createReservation.response.body.id}}

### Ticket Service - Cancelar reserva
DELETE {{ticket}}/api/reservations/{{reservationId}}
Authorization: Bearer {{accessToken}}

### Ticket Service - Commit reserva (gera tickets)
POST {{ticket}}/api/reservations/{{reservationId}}/commit
Authorization: Bearer {{accessToken}}

### Ticket Service - Regenerar QR do ticket
POST {{ticket}}/api/tickets/{ticketId}/qr/regenerate
Authorization: Bearer {{accessToken}}

### Ticket Service - Transferir ticket
POST {{ticket}}/api/tickets/{ticketId}/transfer?fromUser=00000000-0000-0000-0000-000000000000&toUser=22222222-2222-2222-2222-222222222222
Authorization: Bearer {{accessToken}}
