### Health
GET http://localhost:8086/s/api/ticket/_health
Accept: application/json

### Criar reserva
POST http://localhost:8086/api/reservations?userId=123e4567-e89b-12d3-a456-426614174000&eventId=11111111-1111-1111-1111-111111111111&ttlSeconds=300
Content-Type: application/json

[
  "A1",
  "A2"
]


### Get Reservation
GET http://localhost:8086/api/reservations/95d2e2bd-fb5d-45ab-bc8a-51c3ce85d671
Accept: application/json

### Cancel Reservation
DELETE http://localhost:8086/api/reservations/95d2e2bd-fb5d-45ab-bc8a-51c3ce85d671
Accept: application/json

### Commit Reservation
POST http://localhost:8086/api/reservations/2f3afbfd-5765-4171-a5ee-826c8fa8da0f/commit
Accept: application/json

### Get Ticket
GET http://localhost:8086/api/tickets/75fb1695-b232-4a9d-85bb-e79c0fefd359
Accept: application/json


