### Health
GET http://localhost:8083/s/api/events/_health
Accept: application/json

### Listar eventos
GET http://localhost:8083/api/events
Accept: application/json

### Criar evento
POST http://localhost:8083/api/events
Content-Type: application/json

{
  "name": "Vasco x Time Exemplo",
  "date": "2025-12-01T20:00:00",
  "venue": "São Januário"
}
